### ISSUE TITLE
Triginometric functions and pi

### ISSUE THREAD

**Issue by juuljuul** [Flipez/rocket-lang#104]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I cannot calculate sine, cosine and tangens with rocket lang

**Describe the solution you'd like**
I would like to have the feature to be able to calculate sin, cos and tan in rocket-lang. Furthermore, the number pi is required to solve 

Example:
```
sin(0) = 0
sin(pi) = 1
cos(0) = 1
tan(x) = sin(x)/cos(x)
```

If you have these functions, you might need the inverse functions arcsin, arccos and arctan

**Comment by Flipez** [comment]
Implemented with #108
