### ISSUE TITLE
2D array access should work within one index operation

### ISSUE THREAD

**Issue by Flipez** [Flipez/rocket-lang#115]
**Describe the bug**
2D array access should work within one index operation

**Program to repoduce**
[rocket-lang program to reproduce the behavior](https://play.rocket-lang.org/?share=YSA9IFtbMSwyXSxbMyw0XV0KcHV0cyhhKQphWzBdWzBdID0gMApwdXRzKGEp)

**Version:**
 - next

**Comment by MarkusFreitag** [comment]
Please make sure that the fix not only works for 2D but for deeper nested arrays in general.

**Comment by MarkusFreitag** [comment]
The bug is not limited to arrays, also appears for nested dictionaries or nested indexable objects in general.
