### ISSUE TITLE
Add version-string to release-filenames

### ISSUE THREAD

**Issue by Kjarrigan** [Flipez/rocket-lang#12]
At the moment all releases are named the same so I have to install/unpack it to determine which version I actually have which is a bit cumbersome.

So please change: `rocket-lang_linux_amd64.deb` to something like `rocket-lang-v0.9.7_linux_amd64.deb`

**Comment by Flipez** [comment]
added with https://github.com/Flipez/rocket-lang/commit/4a7322a033c2a39d55a9a03bf12c83b6798284d4
