### ISSUE TITLE
Nested loop seems to be broken

### ISSUE THREAD

**Issue by Flipez** [Flipez/rocket-lang#120]
**Describe the bug**
Nested loop seems to be broken

**Program to repoduce**
[rocket-lang program to reproduce the behavior](https://play.rocket-lang.org/?share=ZGVmIG5ldyhzaXplKQoJYSA9IFtdCglmb3JlYWNoIGkgaW4gc2l6ZQoJCWIgPSBbXQoJCWZvcmVhY2ggaiBpbiBzaXplCgkJCWIueW9pbmsoW10pCgkJZW5kCgkJYS55b2luayhiKQoJZW5kCglyZXR1cm4gYQplbmQKCm5ldyg1KQ%3D%3D)

**Version:**
 - next

**Comment by MarkusFreitag** [comment]
Nested loops are not broken in general, just when you use the same variable in them. [reproducer](https://play.rocket-lang.org/?share=Ly8gd29ya2luZyBuZXN0ZWQgbG9vcApmb3JlYWNoIGkgaW4gMwoJZm9yZWFjaCBqIGluIDMKCQlwdXRzKGkucGx6X3MoKSArICItIiArIGoucGx6X3MoKSkKCWVuZAoJcHV0cygiLS0tLS0iKQplbmQKCnB1dHMoIi0tLS0tLS0tLS0tLS0tLS0tLS0iKQoKLy8gYnJva2VuIG5lc3RlZCBsb29wCnRpbWVzID0gMwpmb3JlYWNoIGkgaW4gdGltZXMKCWZvcmVhY2ggaiBpbiB0aW1lcwoJCXB1dHMoaS5wbHpfcygpICsgIi0iICsgai5wbHpfcygpKQoJZW5kCglwdXRzKCItLS0tLSIpCmVuZA%3D%3D)
