### ISSUE TITLE
Improve file handling

### ISSUE THREAD

**Issue by Flipez** [Flipez/rocket-lang#35]
Implement and adjust file methods:

- [x] `file.read(INT)` takes number of bytes and reads the bytes from the position
- [x] `file.seek(INT, INT)` seeks the cursor for arg 0 amount from arg  1 position
- [x] `file.content()` reads the complete file as string
- [x] `file.position()` returns the current cursor position

**Comment by MarkusFreitag** [comment]
`file.write(STRING)`

alternative for seeking `file.seek(INT, BOOL)` with true being absolute and false=relative counting
