### ISSUE TITLE
Feature Request: Add CLI args / methods

### ISSUE THREAD

**Issue by Kjarrigan** [Flipez/rocket-lang#52]
Right now RocketLang (v0.13.0) starts a REPL when no argument is provided or executes a given file but it would be nice to have some basic options and help actually explaning that behaviour so something like

```
$ rocket-lang -h

Usage: rocket-lang [switches] [programfile] [-- arguments]

-h, --help
-e, --exec 'command'
-v, --version
```

**Comment by Flipez** [comment]
What kind of commands would you like to execute? Normal program code?
