### ISSUE TITLE
Bug: open() with two arguments does not work

### ISSUE THREAD

**Issue by Kjarrigan** [Flipez/rocket-lang#54]
## Stats
* RocketLang: `0.14.1`
* Plattform: `Linux home 5.4.0-94-generic`
* OS: `Ubuntu 20.04.3 LTS`
* Installed RocketLang via: `*.deb Package`

## Problem
Withouth the optional second argument open works just fine

```javascript
open("/tmp/foo").content()
```

but adding it like shown in the docs

```javascript
open("main.go", "ro").content()
```

breaks with `ERROR: Failed to invoke method: content`

**Comment by MarkusFreitag** [comment]
`ro` is not a valid mode, you can choose from `r, w, wa, rw, rwa`.

The real bug here is that the initial error of `open()` is not shown and it tries to call `content()` at the returned error.
