### ISSUE TITLE
Parser: add more errors for bad syntax

### ISSUE THREAD

**Issue by RaphaelPour** [Flipez/rocket-lang#68]
@MarkusFreitag and I found some cases where the parser returns within `foreach` without an error. I'm curious if you want that as uncatched errors lead to  'valid code' that should be rejected.

- [parser/foreach#36](https://github.com/Flipez/rocket-lang/blob/879315680bdae45dd708fcc216c73cbac3c250a0/parser/foreach.go#L36) Should it be allowed to have a `foreach` statement without the `in` keyword?
- [parser/foreach#42](https://github.com/Flipez/rocket-lang/blob/879315680bdae45dd708fcc216c73cbac3c250a0/parser/foreach.go#L24) Should it be allowed to just ignore the number after `in`? 

Maybe there are more cases in other places. Fixing them may bring us near to the `puts puts` phenomenon.

**Comment by Flipez** [comment]
I've added an specific error message for the missing `in` keyword.

Covering the second case is tricky as newlines are completely optional. Therefore it is close to impossible to check if the expession after `in` is meant to be the body or not. If the body starts with an object that is iterable it would be valid code:

```js
foreach i, v in
  5
  puts(v)
end
```

produces the following, valid output:

```js
0
1
2
3
4
5
```
